# Generated by Django 4.2.6 on 2023-10-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_genre', models.CharField(max_length=100)),
                ('movie_year', models.IntegerField()),
                ('movie_rating', models.FloatField()),
                ('movie_release_date', models.DateField()),
                ('movie_language', models.CharField(max_length=100)),
                ('movie_cast', models.CharField(max_length=100)),
                ('movie_director', models.CharField(max_length=100)),
                ('movie_runtime', models.IntegerField()),
                ('movie_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
