# Generated by Django 5.0 on 2023-12-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_movie_cast_alter_movie_movie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
